title:            Sunghyun Kim Curriculum vitae
description:      Curriculum vitae of Sunghyun Kim
url:              abinitioskim.github.com
signoff:          Sunghyun Kim # Your name.
disqus_shortname: # disqus comment thread for post header options. ( leave blank if unwanted. )
facebook_appid:   # appid for like button, remove from /_includes/share.html if unwanted.
google_analytics: # set tracking, remove from /javascripts/basic.js if unwanted.

links:
  - name:         CV 
    url:          /
  - name:         Presentation
    url:          /presentation
  - name:         GitHub
    url:          http://github.com/abinitioskim
  - name:         Phys_ko
    url:          /phys_ko
    external:     true
highlighter:      pygments
permalink:        pretty
markdown:         redcarpet
redcarpet:
  extensions:
    - smart
